"""
Analyze a conversation to detect branches using BranchExtractor
"""

from chatroutes_autobranch.branch_detection import BranchExtractor

# The conversation to analyze
conversation = """
currently llm search web to gather facts and details. with the growing number of llm users what if people stop creating those websites. how will llm find details about new things ideas etc.

You said:
most of the content these days is being generated by llm, so we are loosing humans in this loop. humans are no longer incetivised to create own information, they use llm

You said:
challenged is how to verify if a content is purely and honestly created by humans

You said:
where did you get this "🌱 4. The Philosophical Layer

Even if we technically solve provenance, a deeper question remains:
What counts as "human"?
If you use AI to summarize your thoughts but the ideas are yours — is that still "human"?
We may need a spectrum of authorship instead of a binary:

🧍‍♂️ Human-origin

🧍‍♂️🤖 Human + AI co-creation

🤖 AI-origin

And those labels could become cultural norms, much like "organic" vs "synthetic" food labeling."

You said:
yes i would like to know more about the origin and research around it

You said:
yes i would like to write an article based on the available credible research on this topic and especially ideas how can humans keep their value.

You said:
here is my rough draft, probably not making too much sense "With all the hype of Gen AI these days and reading daily about many layoffs or "restructuring" many of us are wondering what is our future? If there is a new tech revolution on the horizon which is going to disrupt the job market then what will be new jobs? what skills i should learn? where are those jobs?

Everyone has lot of quesitons but no one has any good answer. Ofcourse we, humans are good at what create and innovate more, with or without considering its consequences. this is most innate nature of human to create something. Creation is often referred as innovation. that does not happen in a vaccum. We observe our surroundings, combine two or more things together, explore different combinations and then one of those combinations clicks and lead to a transformation of society.

Gen AI can help us find two or more things to combine, even explore different combinations but transformation is still in our hand. But there is a step even before that. Who asked us to observe? Gen AI cannot do that yet.

All these models are getting better and better everyday but they still not there where they can start creating something completely new without any guidance from human. it is human which still have the seed of idea and desire to accomplish something and for that it uses tools which happen to be AI. Gen AI is a means to get to the end, it is not the end."

You said:
i want to add historical references, studies, graphs and show some examples from past where machines enabled humans to get better at things.

You said:
so if you are typical office worker who creates reports, spreadsheets, budgets and you have analytical skills today to certain job what should he do. he or she does not think he or she is creative because they are performing tasks which get them, their boss, their company to the end. what will be these kind of people doing when all these tasks are done by ai.

You said:
does it mean everyone will have freedom to perform the task they want

You said:
how this wave of labor changed from farmlands to factories to officies

You said:
yes

You said:
so how does it help us to know what exactly we will be doing in future and what new roles will be created and what should student study now

You said:
so let's take some examples of some concrete roles and see how those people should change for future

You said:
lets focus on those traditioanal roles of accountant, lawyer, doctors etc. should they still study what they study today

You said:
ok now i am thinking to divide this into multiple articles and start with the definition of creativity, human creativity, meaning of work, creation of value and how value creation is changing. in that we can give different examples of past to find patterns. in another article we can dive into different professions and what possible new changes appearing, what new roles will be created. in another article we will see how will a traditional company will look and how a new modern company will look like probably simulate their work to give insight.

You said:
do you have more suggestions how get a better understanding to explain something more before, middle and after all this.

You said:
What should write for part 1. I need to back my words with different writers book, trusted data source. Article shows the breadth and width from different angles.
"""

def main():
    print("=" * 80)
    print("BRANCH DETECTION ANALYSIS")
    print("=" * 80)
    print()

    # Create extractor with default patterns
    extractor = BranchExtractor()

    # Extract branch points
    branch_points = extractor.extract(conversation)

    print(f">> DETECTED {len(branch_points)} BRANCH POINTS")
    print()
    print("=" * 80)

    if not branch_points:
        print()
        print("WARNING: No explicit branch points detected in this conversation.")
        print()
        print("This is expected! The conversation has narrative/topic branches,")
        print("but no explicit decision points like:")
        print("  - Numbered lists (1. Option A, 2. Option B)")
        print("  - Disjunctions (use Flask or FastAPI)")
        print("  - Conditionals (if X then Y else Z)")
        print()
        print("Your conversation contains IMPLICIT branching through:")
        print("  - Topic shifts (LLM data -> human value -> article writing)")
        print("  - Decision points (curiosity -> research -> article planning)")
        print("  - Scope changes (philosophical -> practical)")
        print()
        print("To analyze this type of branching, you would need:")
        print("  1. LLMBranchParser with a custom prompt for narrative analysis")
        print("  2. Or a specialized conversation flow analyzer")
        print()
    else:
        for i, branch in enumerate(branch_points, 1):
            print(f"\n>> BRANCH POINT {i}")
            print(f"   ID: {branch.id}")
            print(f"   Type: {branch.type}")
            print(f"   Options: {branch.option_count}")

            print(f"   \n   Context:")
            context = branch.context[:200] + "..." if len(branch.context) > 200 else branch.context
            print(f"   {context}")

            print(f"   \n   Options:")
            for opt in branch.options:
                print(f"      - {opt.label}")

            print()
            print("-" * 80)

        # Summary statistics
        print("\n" + "=" * 80)
        print("SUMMARY STATISTICS")
        print("=" * 80)

        stats = extractor.get_statistics(branch_points)

        print(f"\n>> Total Branch Points: {stats['total_branch_points']}")
        print(f">> Total Options: {stats['total_options']}")
        print(f">> Max Leaves: {stats['max_leaves']}")
        print(f">> Avg Options/Branch: {stats['avg_options_per_branch']:.2f}")

        print("\n>> Branch Types:")
        for btype, count in sorted(stats['by_type'].items(), key=lambda x: x[1], reverse=True):
            print(f"   {btype}: {count}")

    print("\n" + "=" * 80)

if __name__ == "__main__":
    main()
